name:  Trigger AI Platform Job

on:
  pull_request:
    paths:
    - trainer

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: christineoo-test-github-action

jobs:
  setup-build-deploy:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        project_id: ${{ secrets.PROJECT_ID }}

    # list ai-platform jobs
    - name: List jobs
      run: |-
        gcloud ai-platform jobs list

    # submit ai-platform jobs
    - name: submit jobs and check status
      env:
        JOB_NAME: christineoo_test_${{ steps.date.outputs.date }}
      run: |-
        make gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }} job_name=$JOB_NAME submit_job

        bash ./job_status.sh ${{ secrets.PROJECT_ID }} $JOB_NAME
