name:  Trigger AI Platform Job

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: christineoo-test-github-action

jobs:
  setup-build-deploy:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        project_id: ${{ secrets.PROJECT_ID }}

    # list ai-platform jobs
    - name: List jobs
      run: |-
        gcloud ai-platform jobs list

    # submit ai-platform jobs
    - name: submit jobs and check status
      env:
        JOB_NAME: christineoo_test_${{ steps.date.outputs.date }}
      run: |-
        make gcs_bucket_name=${{ secrets.GCS_BUCKET_NAME }} job_name=$JOB_NAME submit_job
        status= make job_name=$JOB_NAME project_id=${{ secrets.PROJECT_ID }} curl_status
        while [ "$status" != "SUCCEEDED" ]
        do
          echo "before status:" $status
          sleep 60
          status= make job_name=$JOB_NAME project_id=${{ secrets.PROJECT_ID }} curl_status
          echo "current status:" $status
        done
    #    timeout 6 sleep 5 || make job_name=$JOB_NAME project_id=${{ secrets.PROJECT_ID }} curl_status

    # check ai-platform job status
    # - name: check job status
    #   run: |-
    #     timeout 6 sleep 5 || make curl_status
